# Generated by Django 3.2.7 on 2022-06-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='amount_fee_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='date_of_admission',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
