# Generated by Django 3.2.7 on 2022-06-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_students_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.AlterField(
            model_name='students_info',
            name='Roll_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
