# Generated by Django 3.2.7 on 2022-06-21 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_auto_20220621_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
